#!/data/data/com.termux/files/usr/bin/sh
export DISPLAY=:1
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
[ -f "$HOME/.Xresources" ] && xrdb $HOME/.Xresources
dbus-launch --exit-with-session xfce4-session &
